--bai 1.1.1
SELECT DEAN.TENDEAN, CAST(SUM(PHANCONG.THOIGIAN) AS decimal(5, 2)) AS [Tổng giờ làm]
FROM DEAN INNER JOIN PHANCONG ON DEAN.MADA = PHANCONG.MADA
GROUP BY DEAN.TENDEAN

--bai 1.1.2
SELECT DEAN.TENDEAN, CAST(SUM(PHANCONG.THOIGIAN) AS varchar) AS [Tổng giờ làm]
FROM DEAN INNER JOIN PHANCONG ON DEAN.MADA = PHANCONG.MADA
GROUP BY DEAN.TENDEAN

--bai 1.2.1
SELECT PHONGBAN.MAPHG, PHONGBAN.TENPHG, CAST(AVG(NHANVIEN.LUONG) AS decimal(15, 2)) AS 'Lương trung bình'
FROM NHANVIEN INNER JOIN PHONGBAN ON NHANVIEN.PHG = PHONGBAN.MAPHG
GROUP BY PHONGBAN.MAPHG, PHONGBAN.TENPHG

--BAI 1.2.2

SELECT PHG,CONVERT(VARCHAR(40),CAST(AVG(LUONG) AS MONEY),1) FROM NHANVIEN GROUP BY PHG;

--BAI 2.1.1
SELECT DEAN.TENDEAN, CEILING(SUM(PHANCONG.THOIGIAN)) AS [Tổng giờ làm]
FROM DEAN INNER JOIN PHANCONG ON dbo.DEAN.MADA = dbo.PHANCONG.MADA
GROUP BY DEAN.TENDEAN

--BAI 2.1.2
SELECT DEAN.TENDEAN, FLOOR(SUM(PHANCONG.THOIGIAN)) AS [Tổng giờ làm]
FROM DEAN INNER JOIN PHANCONG ON dbo.DEAN.MADA = dbo.PHANCONG.MADA
GROUP BY DEAN.TENDEAN

--BAI 2.1.3
SELECT DEAN.TENDEAN, ROUND(SUM(PHANCONG.THOIGIAN), 2) AS [Tổng giờ làm]
FROM DEAN INNER JOIN PHANCONG ON DEAN.MADA = PHANCONG.MADA
GROUP BY DEAN.TENDEAN

--BAI 2.2
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS 'Họ tên nv có lương trung bình trên mức lương trung bình của phòng "Nghiên cứu"', LUONG
FROM NHANVIEN
WHERE (LUONG >(SELECT ROUND(AVG(NHANVIEN_1.LUONG), 2) AS 'Lương trung bình của nhân viên là :'
FROM NHANVIEN AS NHANVIEN_1 INNER JOIN PHONGBAN ON NHANVIEN_1.PHG = PHONGBAN.MAPHG
WHERE(PHONGBAN.TENPHG = N'Nghiên cứu')))

--BAI 3
	SELECT UPPER(HONV),TENLOT,TENNV,DCHI
	FROM NHANVIEN,THANNHAN
	WHERE MA_NVIEN=MANV
	GROUP BY HONV,TENLOT,TENNV,DCHI
	HAVING COUNT(THANNHAN.MA_NVIEN)>2
	GO
	SELECT HONV,LOWER(TENLOT),TENNV,DCHI
	FROM NHANVIEN,THANNHAN
	WHERE MA_NVIEN=MANV
	GROUP BY HONV,TENLOT,TENNV,DCHI
	HAVING COUNT(THANNHAN.MA_NVIEN)>2
	GO
	 SELECT DCHI FROM NHANVIEN
  SELECT DCHI,CHARINDEX(' ',DCHI) FROM NHANVIEN
  SELECT DCHI, LEFT(DCHI,CHARINDEX(' ',DCHI)) AS 'SỐ NHÀ'FROM NHANVIEN

 --BÀI 4
  GO
  SELECT HONV,TENLOT,TENNV
  FROM NHANVIEN
  where Year(NGSINH) Between 1960 and 1965
  GO
  SELECT HONV,TENLOT,TENNV,YEAR(GETDATE())-YEAR(NGSINH) AS TUOI
  FROM NHANVIEN
  GO
  SELECT TENPHG, CONVERT(VARCHAR, NG_NHANCHUC,105) AS 'NGAY SINH',HONV,TENLOT,TENNV,COUNT(*) NHANVIEN
  FROM PHONGBAN, NHANVIEN
  WHERE   MANV=TRPHG and MAPHG=PHG
  GROUP BY TENPHG,NG_NHANCHUC,HONV,TENLOT,TENNV