--BAI 1.1
DECLARE @TK TABLE (PHG INT, LTB FLOAT);
INSERT INTO @TK
	SELECT PHG, AVG(LUONG) AS LTB FROM NHANVIEN GROUP BY PHG;
SELECT TENNV ,'NHANGT'=IIF(LUONG>LTB, 'KHONG TANG LUONG','TANGLUONG')
	FROM NHANVIEN a inner join @TK b ON a.PHG =b.PHG;

--BAI 1.2
DECLARE @TK1 TABLE (PHG INT, LTB FLOAT);
INSERT INTO @TK1
	SELECT PHG,AVG(LUONG) AS LTB FROM NHANVIEN GROUP BY PHG;
SELECT 'CHUCVU'=IIF(LUONG>b.LTB, 'TRUONGPHONG','NHANVIEN'),TENNV,LUONG
	FROM NHANVIEN a inner join @TK1 b ON a.PHG=b.PHG;
--BAI 1.3
SELECT IIF(PHAI=N'NAM','MR.','MS.')+TENNV AS 'TEN'FROM NHANVIEN;
--BAI1.4
SELECT TENNV,LUONG, 'THUE'=CASE
WHEN LUONG BETWEEN 0AND 25000 THEN LUONG* 0.1
WHEN LUONG BETWEEN 25000 AND 30000 THEN LUONG* 0.12
WHEN LUONG BETWEEN 30000 AND 40000 THEN LUONG* 0.15
WHEN LUONG BETWEEN 40000 AND 50000 THEN LUONG* 0.2
ELSE LUONG* 0.25
END
FROM NHANVIEN;

--BAI2.1
DECLARE @MAX INT, @NUM INT;
SELECT @MAX =MAX(CAST (MANV AS INT )) FROM NHANVIEN;
SET @NUM =1;
WHILE @NUM <=@MAX 
BEGIN 
	IF @NUM % 2=0
		SELECT MANV,HONV,TENLOT,TENNV FROM NHANVIEN WHERE CAST(MANV AS INT)=@NUM;
	SET @NUM =@NUM +1;
END;

--BAI 2.2
DECLARE @MAX1 INT, @NUM1 INT;
SELECT @MAX1 =MAX(CAST (MANV AS INT )) FROM NHANVIEN;
SET @NUM1 =1;
WHILE @NUM1 <=@MAX1 
BEGIN 
	IF @NUM1=4
	BEGIN
	SET @NUM1 =@NUM1 +1;
	CONTINUE;
	END
	IF @NUM1 % 2=0
		SELECT MANV,HONV,TENLOT,TENNV FROM NHANVIEN WHERE CAST(MANV AS INT)=@NUM1;
	SET @NUM1 =@NUM1 +1;
END;
--BAI3.1
BEGIN TRY
INSERT INTO PHONGBAN(TENPHG,MAPHG,TRPHG,NG_NHANCHUC)
	VALUES(N'SẢN XUẤT',9,'009','2020-03-02');
	PRINT N'DỮ LIỆU CHÈN THÀNH CÔNG'
	END TRY
	BEGIN CATCH
	PRINT 'DỮ LIỆU CHÈN VÀO THẤT BẠI'
	END CATCH;
--BAI3.2

BEGIN TRY 
DECLARE @CHIA INT;
SET @CHIA =55/0;
END TRY 
BEGIN CATCH
DECLARE @ERRORMESSAGE NVARCHAR(2000), @ERRORSEVERITY INT, @ERRORSTATE INT;
SELECT @ERRORMESSAGE = ERROR_MESSAGE(),
@ERRORSEVERITY =ERROR_SEVERITY(),
@ERRORSTATE=ERROR_STATE();
RAISERROR(@ERRORMESSAGE,@ERRORSEVERITY,@ERRORSTATE);
END CATCH;

--BÀI 4
DECLARE @tong1 int = 0,@d INT = 10,@F INT
SET @F = 1
WHILE (@f<=@d)
BEGIN
if (@f %2 =0)
SET @tong1 = @tong1 + @f
SET @f = @f + 1 
if(@f = 4)
SET @tong1 = @tong1 - 4
END
PRINT ('Ket qua la: ' )
PRINT @tong1